GET http://localhost:5000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsIm5hbWUiOiJkZW5peiIsImVtYWlsIjoiZW1haWxAZ21haWwuY29tIiwiaWF0IjoxNjM3Mzc1Njg2LCJleHAiOjE2MzczNzU3MDZ9.1i-PwwsTHExo7lUYOUAmf7jUlk97PpTGWtW4RVcdky4

###
POST http://localhost:5000/users
Content-Type: application/json

{
    "email" : "email@gmail.com",
    "password" : "12345"
}

###
POST http://localhost:5000/login
Content-Type: application/json

{
    "email" : "email@gmail.com",
    "password" : "12345"
}

###
GET http://localhost:5000/token

###
DELETE http://localhost:5000/logout